### ISSUE TITLE
init command fails

### ISSUE THREAD

**Issue by entropiajp** [marcy-terui/lamvery#51]
Hi.

```shell
$ python -V
Python 2.7.10
$ pip list | grep lamvery
lamvery (0.12.3)
$ lamvery init
ERROR:root:'Namespace' object has no attribute 'alias'
Traceback (most recent call last):
  File "/Users/koyama/.pyenv/versions/xxxxxx/lib/python2.7/site-packages/lamvery/cli.py", line 250, in main
    args.func(args)
  File "/Users/koyama/.pyenv/versions/xxxxxx/lib/python2.7/site-packages/lamvery/cli.py", line 24, in init
    InitAction(args).action()
  File "/Users/koyama/.pyenv/versions/xxxxxx/lib/python2.7/site-packages/lamvery/actions/init.py", line 12, in __init__
    super(InitAction, self).__init__(args)
  File "/Users/koyama/.pyenv/versions/xxxxxx/lib/python2.7/site-packages/lamvery/actions/base.py", line 23, in __init__
    self._alias = args.alias
AttributeError: 'Namespace' object has no attribute 'alias'
'Namespace' object has no attribute 'alias'
```

Is there anything required to do before `lamvery init`?

**Comment by marcy-terui** [comment]
Hi,

Thank you for your reporting.
It is a bug... :cry: 

So, I fixed it and released the new version [0.12.4](https://pypi.python.org/pypi/lamvery/0.12.4)
Please upgrade to  the new version.

```shell
pip install --upgrade lamvery
```

**Comment by entropiajp** [comment]
Thank you for quick fix :+1:

**Comment by marcy-terui** [comment]
:smiley_cat:
