### ISSUE TITLE
Jinja 2.9 causes lamvery to fail

### ISSUE THREAD

**Issue by erichennings** [marcy-terui/lamvery#74]
When I use Jinja 2.9 in my own project (i.e. with the requirements.txt shown below) it appears to cause problems when running lamvery deploy - see ouput below.

Removing the requirements.txt line or setting it to 2.8.1 makes the error disappear.

requirements.txt snippet:
```
Jinja2==2.9
```

output of lamvery deploy:
```shell
(.venv) EricMBP:lambda-prototype eric$ lamvery deploy -a test
  File "/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

ERROR:root:[Errno 2] No such file or directory: '/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/jinja2/asyncfilters.pyc'
Traceback (most recent call last):
  File "/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/lamvery/cli.py", line 336, in main
    args.func(args)
  File "/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/lamvery/cli.py", line 39, in deploy
    DeployAction(args).action()
  File "/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/lamvery/actions/deploy.py", line 43, in action
    zipfile = builder.build()
  File "/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/lamvery/build.py", line 68, in build
    self._archive_dir(zipfile, p)
  File "/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/lamvery/build.py", line 117, in _archive_dir
    zipfile.writepy(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1418, in writepy
    self.write(fname, arcname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: '/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/jinja2/asyncfilters.pyc'
[Errno 2] No such file or directory: '/Users/eric/sources/lambda-prototype/.venv/lib/python2.7/site-packages/jinja2/asyncfilters.pyc'
```

**Comment by ijin** [comment]
@erichennings  It's probably a pip/jinja compatability problem.

https://github.com/marcy-terui/lamvery/pull/69
